import type { ChannelProfile, ComplianceRule, RuleSource } from "./domain";

export const channelProfiles: ChannelProfile[] = [
  { id: "amazon-us", name: "Amazon US", market: "US", language: "en-US", imageRequirements: { minWidth: 1000, minHeight: 1000, mainBackground: "#FFFFFF", maxImages: 9 }, listingLimits: { titleMin: 50, titleMax: 200, bulletMax: 5 } },
  { id: "tiktok-us", name: "TikTok Shop US", market: "US", language: "en-US", imageRequirements: { minWidth: 600, minHeight: 600, mainBackground: "#FFFFFF", maxImages: 9 }, listingLimits: { titleMin: 25, titleMax: 200 } },
  { id: "shopify-us", name: "Shopify US", market: "US", language: "en-US", imageRequirements: { minWidth: 800, minHeight: 800, mainBackground: "flexible", maxImages: 250 }, listingLimits: { titleMin: 20, titleMax: 255 } },
];

export const ruleSources: RuleSource[] = [
  { id: "ftc-truth", authority: "FTC", title: "Advertising and Marketing", url: "https://www.ftc.gov/business-guidance/advertising-marketing", jurisdiction: "United States", categories: ["*"], version: "snapshot-2026-08-07", fetchedAt: "2026-08-07", excerpt: "Advertising claims must be truthful, not misleading, and supported by evidence.", contentHash: "sha256:ebe05b92a56cf0580fa19230933c8a2fa253ab3bfe36893a9430ac5d565eff08" },
  { id: "ftc-health", authority: "FTC", title: "Health Products Compliance Guidance", url: "https://www.ftc.gov/business-guidance/resources/health-products-compliance-guidance", jurisdiction: "United States", categories: ["beauty", "food", "supplement", "health"], version: "snapshot-2026-08-07", fetchedAt: "2026-08-07", excerpt: "Health-related benefit and safety claims require appropriate substantiation.", contentHash: "sha256:0562e09956d5118867daa45626f6e4033716b4d22de9858d0fd81cb129fe7808" },
  { id: "fda-cosmetics", authority: "FDA", title: "Cosmetics Labeling Claims", url: "https://www.fda.gov/cosmetics/cosmetics-labeling/cosmetics-labeling-claims", jurisdiction: "United States", categories: ["beauty", "cosmetics", "personal-care"], version: "snapshot-2026-08-07", fetchedAt: "2026-08-07", excerpt: "Cosmetic claims must be truthful and must not imply unapproved drug treatment.", contentHash: "sha256:214b62b0e763cacc84a47822a9edc51f65021e4fcac52c5842dae3d3c7ba9c1c" },
  { id: "cpsc-sellers", authority: "CPSC", title: "Online Sellers’ Safety Guide", url: "https://www.cpsc.gov/Business--Manufacturing/Online-Sellers-Safety-Guide", jurisdiction: "United States", categories: ["consumer-goods", "children", "appliance", "electronics"], version: "snapshot-2026-08-07", fetchedAt: "2026-08-07", excerpt: "Online sellers must identify applicable consumer-product safety, testing, certification, and recall duties.", contentHash: "sha256:220f9501c6605c55a064e40657abe914a7d6b4192db26d6a9fac745b11cc1e85" },
  { id: "amazon-images", authority: "Amazon", title: "Product Image Requirements", url: "https://sellercentral.amazon.com/help/hub/reference/G1881", jurisdiction: "United States", platform: "amazon-us", categories: ["*"], version: "snapshot-2026-08-07", fetchedAt: "2026-08-07", excerpt: "Amazon main images require a pure white background and prohibit added text, graphics, or watermarks.", contentHash: "sha256:bb4e32c84a578e8eb73ab3b04427ed07fb5c081993a0da36dd9f0812d473c9f1" },
  { id: "tiktok-listing", authority: "TikTok Shop", title: "Product Listing Policy", url: "https://seller-us.tiktok.com/university/essay?knowledge_id=3196690250417921", jurisdiction: "United States", platform: "tiktok-us", categories: ["*"], version: "snapshot-2026-08-07", fetchedAt: "2026-08-07", excerpt: "TikTok Shop listings and images must accurately represent the product and avoid misleading claims.", contentHash: "sha256:fde955345241746eeb144444eb5307589a214da702017df8da21ee8cda9425f2" },
  { id: "shopify-media", authority: "Shopify", title: "Product media guidance", url: "https://help.shopify.com/en/manual/products/product-media", jurisdiction: "United States", platform: "shopify-us", categories: ["*"], version: "snapshot-2026-08-07", fetchedAt: "2026-08-07", excerpt: "Shopify product media should accurately represent the product and be suitable for storefront delivery.", contentHash: "sha256:966d92565f7a9e11bad889c93b5ca94755e28217384383ec65672ff6dd0a38c2" },
];

export const complianceRules: ComplianceRule[] = [
  { id: "claim-absolute", sourceId: "ftc-truth", scope: "advertising", target: "all", severity: "high", categories: ["*"], channels: ["amazon-us", "tiktok-us", "shopify-us"], pattern: "\\b(100%|guaranteed|number\\s*1|no\\.?\\s*1|best|perfect|cure|risk[- ]free)\\b", message: "发现可能缺少充分证据的绝对化、排名或保证性宣称。", suggestion: "改为可验证的商品结构、条件或测试结果描述。" },
  { id: "fact-duration", sourceId: "ftc-truth", scope: "facts", target: "all", severity: "medium", categories: ["*"], channels: ["amazon-us", "tiktok-us", "shopify-us"], pattern: "\\b(up to|lasts?|per charge|hours?|minutes?)\\b", message: "发现需要商品事实或测试材料支持的量化宣称。", suggestion: "关联已确认事实和证据，或删除未经确认的数字。" },
  { id: "health-treatment", sourceId: "fda-cosmetics", scope: "category", target: "all", severity: "high", categories: ["beauty", "cosmetics", "personal-care"], channels: ["amazon-us", "tiktok-us", "shopify-us"], pattern: "\\b(treat|heal|cure|repair disease|anti-inflammatory|medical grade)\\b", message: "美妆文案可能构成治疗疾病或影响身体结构/功能的药品宣称。", suggestion: "改为外观、清洁或保湿等化妆品用途表达，并核验支持材料。" },
  { id: "amazon-main-promo", sourceId: "amazon-images", scope: "platform", target: "image", severity: "high", categories: ["*"], channels: ["amazon-us"], message: "Amazon 主图不得包含促销文字、水印或非随售道具。", suggestion: "使用纯白背景，仅保留实际销售商品。" },
  { id: "tiktok-title-clickbait", sourceId: "tiktok-listing", scope: "platform", target: "title", severity: "medium", categories: ["*"], channels: ["tiktok-us"], pattern: "\\b(best seller|buy now|low stock|free gift)\\b", message: "TikTok Shop 标题包含点击诱导或促销表达。", suggestion: "保留准确的品类、属性、规格和使用场景。" },
  { id: "asset-role-facts", sourceId: "ftc-truth", scope: "facts", target: "image", severity: "high", categories: ["*"], channels: ["amazon-us", "tiktok-us", "shopify-us"], message: "尺寸图和特征图只能展示已确认的商品事实，不能用普通商品图替代。", suggestion: "补充并确认对应事实后重新生成，或人工替换为真实素材。" },
];

export function sourceFor(id: string) { return ruleSources.find((source) => source.id === id); }
